[mypy]
python_version = 3.13
ignore_missing_imports = True
show_error_codes = True
pretty = True
exclude = (?x)(^build/)
check_untyped_defs = True
warn_return_any = True
warn_unused_ignores = True
no_implicit_optional = True

[mypy-tests.*]
ignore_errors = True

[mypy-storage.db_channels]
disable_error_code = attr-defined

[mypy-storage.db_tasks]
disable_error_code = attr-defined

[mypy-storage.db_settings]
disable_error_code = attr-defined

[mypy-storage.db_comment_campaigns]
disable_error_code = attr-defined

[mypy-storage.db_join_campaigns]
disable_error_code = attr-defined
